- type: application/vnd.org.wtwta.project
  main: x-golang
  id: x-golang
  version: 0.1.3 # x-golang
  license: GPL-3.0
  urls:
    base:
      - http://github.com/bvberkum/x-golang
    license:
      - https://www.gnu.org/licenses/gpl-3.0.txt
      - https://choosealicense.com/licenses/gpl-3.0/
      - https://opensource.org/licenses/gpl-license
    source-code:
      - http://github.com/bvberkum/x-golang.git
    images:
      - https://hub.docker.com/r/bvberkum/x-golang
    builds:
      - https://travis-ci.org/bvberkum/x-golang
  repositories:
    github: git@github.com:bvberkum/x-golang.git
  scripts:
    init:
      - htd package update
      - vc regenerate
    check:
      - verbosity=1 git-versioning check
    docs:
      - make doc
